services:

  db:
    image: postgres:16

    container_name: inventory_db

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build:
      context: ./backend

    container_name: inventory_backend

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    depends_on:
      - db

  frontend:

    build:
      context: ./frontend

    container_name: inventory_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: